# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import epdsid_pb2 as epdsid__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in epdsid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TestesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChamadaVazio = channel.unary_unary(
                '/Testes/ChamadaVazio',
                request_serializer=epdsid__pb2.Vazio.SerializeToString,
                response_deserializer=epdsid__pb2.Vazio.FromString,
                _registered_method=True)
        self.ValorAbsolutoLong = channel.unary_unary(
                '/Testes/ValorAbsolutoLong',
                request_serializer=epdsid__pb2.Long.SerializeToString,
                response_deserializer=epdsid__pb2.Long.FromString,
                _registered_method=True)
        self.SomaOitoLong = channel.unary_unary(
                '/Testes/SomaOitoLong',
                request_serializer=epdsid__pb2.OitoLong.SerializeToString,
                response_deserializer=epdsid__pb2.Long.FromString,
                _registered_method=True)
        self.InverteString = channel.unary_unary(
                '/Testes/InverteString',
                request_serializer=epdsid__pb2.String.SerializeToString,
                response_deserializer=epdsid__pb2.String.FromString,
                _registered_method=True)
        self.ChamadaComplexo = channel.unary_unary(
                '/Testes/ChamadaComplexo',
                request_serializer=epdsid__pb2.SolicitacaoComplexo.SerializeToString,
                response_deserializer=epdsid__pb2.RespostaComplexo.FromString,
                _registered_method=True)


class TestesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChamadaVazio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValorAbsolutoLong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SomaOitoLong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InverteString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChamadaComplexo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChamadaVazio': grpc.unary_unary_rpc_method_handler(
                    servicer.ChamadaVazio,
                    request_deserializer=epdsid__pb2.Vazio.FromString,
                    response_serializer=epdsid__pb2.Vazio.SerializeToString,
            ),
            'ValorAbsolutoLong': grpc.unary_unary_rpc_method_handler(
                    servicer.ValorAbsolutoLong,
                    request_deserializer=epdsid__pb2.Long.FromString,
                    response_serializer=epdsid__pb2.Long.SerializeToString,
            ),
            'SomaOitoLong': grpc.unary_unary_rpc_method_handler(
                    servicer.SomaOitoLong,
                    request_deserializer=epdsid__pb2.OitoLong.FromString,
                    response_serializer=epdsid__pb2.Long.SerializeToString,
            ),
            'InverteString': grpc.unary_unary_rpc_method_handler(
                    servicer.InverteString,
                    request_deserializer=epdsid__pb2.String.FromString,
                    response_serializer=epdsid__pb2.String.SerializeToString,
            ),
            'ChamadaComplexo': grpc.unary_unary_rpc_method_handler(
                    servicer.ChamadaComplexo,
                    request_deserializer=epdsid__pb2.SolicitacaoComplexo.FromString,
                    response_serializer=epdsid__pb2.RespostaComplexo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Testes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Testes', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Testes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChamadaVazio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Testes/ChamadaVazio',
            epdsid__pb2.Vazio.SerializeToString,
            epdsid__pb2.Vazio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValorAbsolutoLong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Testes/ValorAbsolutoLong',
            epdsid__pb2.Long.SerializeToString,
            epdsid__pb2.Long.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SomaOitoLong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Testes/SomaOitoLong',
            epdsid__pb2.OitoLong.SerializeToString,
            epdsid__pb2.Long.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InverteString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Testes/InverteString',
            epdsid__pb2.String.SerializeToString,
            epdsid__pb2.String.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChamadaComplexo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Testes/ChamadaComplexo',
            epdsid__pb2.SolicitacaoComplexo.SerializeToString,
            epdsid__pb2.RespostaComplexo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
