# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: epdsid.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'epdsid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65pdsid.proto\"\x07\n\x05Vazio\"\x15\n\x04Long\x12\r\n\x05valor\x18\x01 \x01(\x03\"b\n\x08OitoLong\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\x12\t\n\x01\x63\x18\x03 \x01(\x03\x12\t\n\x01\x64\x18\x04 \x01(\x03\x12\t\n\x01\x65\x18\x05 \x01(\x03\x12\t\n\x01\x66\x18\x06 \x01(\x03\x12\t\n\x01g\x18\x07 \x01(\x03\x12\t\n\x01h\x18\x08 \x01(\x03\"\x17\n\x06String\x12\r\n\x05texto\x18\x01 \x01(\t\"=\n\x13SolicitacaoComplexo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\"\"\n\x10RespostaComplexo\x12\x0e\n\x06status\x18\x01 \x01(\t2\xcc\x01\n\x06Testes\x12\x1e\n\x0c\x43hamadaVazio\x12\x06.Vazio\x1a\x06.Vazio\x12!\n\x11ValorAbsolutoLong\x12\x05.Long\x1a\x05.Long\x12 \n\x0cSomaOitoLong\x12\t.OitoLong\x1a\x05.Long\x12!\n\rInverteString\x12\x07.String\x1a\x07.String\x12:\n\x0f\x43hamadaComplexo\x12\x14.SolicitacaoComplexo\x1a\x11.RespostaComplexob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'epdsid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VAZIO']._serialized_start=16
  _globals['_VAZIO']._serialized_end=23
  _globals['_LONG']._serialized_start=25
  _globals['_LONG']._serialized_end=46
  _globals['_OITOLONG']._serialized_start=48
  _globals['_OITOLONG']._serialized_end=146
  _globals['_STRING']._serialized_start=148
  _globals['_STRING']._serialized_end=171
  _globals['_SOLICITACAOCOMPLEXO']._serialized_start=173
  _globals['_SOLICITACAOCOMPLEXO']._serialized_end=234
  _globals['_RESPOSTACOMPLEXO']._serialized_start=236
  _globals['_RESPOSTACOMPLEXO']._serialized_end=270
  _globals['_TESTES']._serialized_start=273
  _globals['_TESTES']._serialized_end=477
# @@protoc_insertion_point(module_scope)
